apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flexjar-frontend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - {{ingress}}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: 100m
      memory: {{memory}}
  liveness:
    path: api/internal/isAlive
  readiness:
    path: api/internal/isReady
  startup:
    path: api/internal/isAlive
    initialDelay: 10
  azure:
    application:
      tenant: nav.no
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "5206a646-a99e-4cd5-90e4-758cf7948cc8" #flex
          - id: "020e6140-6395-430b-9021-65de50e42a0f" #flexjar
          - id: "3a541678-8965-45c4-844b-486a8b9b94a3" #teamsykmelding
    sidecar:
      enabled: true
      autoLogin: false
  accessPolicy:
    outbound:
      rules:
        - application: flexjar-backend
      external:
        - host: slack.com
        - host: api.slack.com
        - host: api.trello.com
        - host: trello.com
  envFrom:
    - secret: flexjar-frontend-slack-webhooks
    - secret: flexjar-frontend-trello-teamsykmelding-secrets
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
